<?php
/* This file was automatically generated by the `grunt libs:cachebuster` command (Thu Sep 22 2022 20:24:47 GMT+0200 (Central European Summer Time)). */
return array(
	'mobx' => '4.15.7',
	'react' => '16.14.0',
	'react-dom' => '16.14.0'
);
