<?php
/* This file was automatically generated by the `grunt libs:cachebuster` command (Thu Sep 22 2022 20:24:47 GMT+0200 (Central European Summer Time)). */
return array(
	'src/public/dist/admin.js' => '3b113a430d329257850364e2acf839a5',
	'src/public/dist/constants.js' => 'bf576bc3a1526c21e81a43dfde695d43',
	'src/public/dist/vendor-admin.js' => 'c42a1481710ec614cf6381fbfad29714',
	'src/public/dist/vendor-widget.js' => 'b5f6b5d424b0d1767877f9db17970e4e',
	'src/public/dist/widget.js' => '64bf9616e00bfa8189e4499baa556fbe',
	'src/public/dist/admin.css' => '1bccf8cebd1f01f87de86e2c41054a2c',
	'src/public/dist/widget.css' => '7ab24d25a56dc3659f279206bb6b64b1',
	'src/public/dev/admin.js' => 'c2a50450ff7073fe3c160f66ad690865',
	'src/public/dev/constants.js' => '7d28facb1f02b8efdaa73a28587421da',
	'src/public/dev/i18n-dir/admin.js' => '92fa710ca1ee2f3f80e74eb1b31ad58c',
	'src/public/dev/i18n-dir/constants.js' => '7d28facb1f02b8efdaa73a28587421da',
	'src/public/dev/i18n-dir/widget.js' => '527ffa6abbe38b381bf974f3b82dc97f',
	'src/public/dev/vendor-admin.js' => '9e4e3a17fc54d7c1cfd4a7cf8c38b0c0',
	'src/public/dev/vendor-widget.js' => 'a3c028f0fc87d00dc8ac563128d043d1',
	'src/public/dev/widget.js' => '527ffa6abbe38b381bf974f3b82dc97f',
	'src/public/dev/admin.css' => '1bccf8cebd1f01f87de86e2c41054a2c',
	'src/public/dev/widget.css' => 'bda071b501601bfcde8825ef8a81408d',
);
